name: server-group

services:
  s1:
    container_name: s1
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      network1:
        ipv4_address: ${SPREAD_SERVER_1_IP}
    environment:
      - SPREAD_IP=${SPREAD_SERVER_1_IP}
    


  s2:
    container_name: s2
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      # network2:
      network1:
        ipv4_address: ${SPREAD_SERVER_2_IP}
    environment:
      - SPREAD_IP=${SPREAD_SERVER_2_IP}

networks:
  network1:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

# network2:
#   driver: bridge
#   ipam:
#     config:
#       - subnet: 192.168.2.0/24
